Add new workflow-launch command
openshift/ci-chat-bot pull request #236
Opened 2021-11-16 23:45 UTC by AlexNPavel

This PR adds a new `workflow-launch` command to the `ci-chat-bot`. This
command allows users to run any workflow they want via the `ci-chat-bot`
as long as that workflow is defined in a simple config file in
`openshift/release`. The workflows config file maps workflows to their
correct platform (and potentially architecture) as well as any
`base_images` that the workflow may require.

/cc @bradmwilliams

2021-11-16 23:45 UTC, AlexNPavel commented
Holding to allow extra required PRs in openshift/release to get merged first.

/hold

2021-11-17 18:31 UTC, bradmwilliams requested changes
Would you mind adding an entry to the FAQ that helps explain how to add a new workflow and potentially a pointer over to the location in `openshift/release`?

2021-12-02 19:04 UTC, AlexNPavel commented
/hold cancel

2021-12-02 19:46 UTC, bradmwilliams approved these changes

2021-12-02 19:46 UTC, merged