[WIP] OCPCRT-193: add support for rosa
openshift/ci-chat-bot pull request #359
Opened 2023-04-03 23:08 UTC by AlexNPavel

This PR adds a `rosa create <version>` command that allows a user whose ID is in a whitelist to launch clusters in the ROSA environment. The `auth` and `done` commands also work on ROSA clusters and if a user has a ROSA cluster, the cluster will show up in the `list` command. The chat-bot keeps passwords that it creates in a secret. When a cluster ID in the secret no longer appears in the list of clusters returned by ROSA, commands to clean up created account-roles and oidc-provider are run.

Currently, the timeout is the same as normal job launches (3 hours + 45 minutes for launching).

2023-04-13 15:49 UTC, AlexNPavel commented
/hold

2023-04-14 12:56 UTC, bradmwilliams requested changes
Just one little nit.  Other than that it looks great!

2023-04-14 12:56 UTC, bradmwilliams commented on hack/run.sh
> +  --impersonate-admin \
AFAICT, This flag is no longer supported.

2023-04-14 13:04 UTC, bradmwilliams commented
There was another test-infra bump this morning, so you'll probably have to rebase as well.  Hopefully, it won't cause you to much grief!

2023-04-14 17:18 UTC, AlexNPavel commented
I rebased to the latest master (no issues from the test-infra bump) and removed the unused flag

2023-04-14 17:59 UTC, AlexNPavel commented
/label tide/merge-method-squash

2023-04-14 18:34 UTC, bradmwilliams commented
/lgtm

2023-04-18 12:22 UTC, bradmwilliams requested changes
Just a typo, but other than that, looks good!

2023-04-18 12:22 UTC, bradmwilliams commented on cmd/ci-chat-bot/main.go
> +	pflag.StringVar(&opt.overrideRosaSecretName, "override-rosa-secret-name", "", "Override the default secert name for rosa cluster tracking. Used for local debugging.")
Typo: `secret` is misspelled

2023-04-18 17:10 UTC, bradmwilliams commented
/lgtm

2023-04-18 17:33 UTC, AlexNPavel commented
/hold cancel

2023-04-18 17:41 UTC, merged